services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://admin:Password!123@db:5432/next-api
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password!123
      POSTGRES_DB: next-api
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
